export const GET_LOCATIONS = 'GET_LOCATIONS';
export const CHANGE_DISPLAY_SAVE_LOCATION = 'CHANGE_DISPLAY_SAVE_LOCATION';
export const CHANGE_DISPLAY_VIEW_LOCATION = 'CHANGE_DISPLAY_VIEW_LOCATION';
export const SAVE_NEW_LOCATION = 'SAVE_NEW_LOCATION';
export const EDIT_LOCATION = 'EDIT_LOCATION';
export const SET_ERROR_NEW_LOCATION = 'SET_ERROR_NEW_LOCATION';
export const SET_SELECTED_LOCATION = 'SET_SELECTED_LOCATION';
export const DELETE_LOCATION = 'DELETE_LOCATION';
export const SET_ACTION_ON_TABLE = 'SET_ACTION_ON_TABLE';
export const SET_ERROR_DELETE_LOCATION = 'SET_ERROR_DELETE_LOCATION';


export const GET_CATEGORIES = 'GET_CATEGORIES';
export const CHANGE_DISPLAY_SAVE_CATEGORY = 'CHANGE_DISPLAY_SAVE_CATEGORY';
export const CHANGE_DISPLAY_VIEW_CATEGORY = 'CHANGE_DISPLAY_VIEW_CATEGORY';
export const SAVE_NEW_CATEGORY = 'SAVE_NEW_CATEGORY';
export const EDIT_CATEGORY = 'EDIT_CATEGORY';
export const SET_ERROR_NEW_CATEGORY = 'SET_ERROR_NEW_CATEGORY';
export const SET_ERROR_DELETE_CATEGORY = 'SET_ERROR_DELETE_CATEGORY';
export const SET_SELECTED_CATEGORY = 'SET_SELECTED_CATEGORY';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';